### ISSUE TITLE
loading file

### ISSUE THREAD

**Issue by jjhesk** [Liroo/react-native-markdown-syntax#1]
What is the way to load or import the markdown file in android production build?

**Comment by Liroo** [comment]
Debug and production build is the same kind. There is some things changing like `__DEV__` = false and compilation flag different, etc.. But the way to import files is NOT changing.

There is an example in the repository

Part of the code:

`npm install react-native-markdown-syntax --save`

```
import Markdown from 'react-native-markdown-syntax';

export default class ... extends Components {
    render(): ReactElement<*> {
         return (
             <Markdown>
                  {Text in markdown}
             </Markdown>
         );
    }
}

```
